### ISSUE TITLE
No preview (no output)

### ISSUE THREAD

**Issue by gremo** [sonnyp/Playhouse#12]
Hi, thanks for your app, it seems so nice to make quick experiements :smiley: 

Unfortunatly, it seems that the app won't work properly on my system. No output at all (default HTML/CSS/JS loaded). Also, the "Inspec element" won't work too (doesn't show up). Any idea? How can I help you finding the problem?

```txt
NAME="Fedora Linux"
VERSION="38 (Thirty Eight)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Thirty Eight)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
```
![Screenshot from 2023-09-29 14-19-36](https://github.com/sonnyp/Playhouse/assets/1532616/67118fd9-bd21-486e-badc-f6d5afed249d)

**Comment by sonnyp** [comment]
Are you using an Nvidia GPU? 

https://bugs.webkit.org/show_bug.cgi?id=228268

**Comment by gremo** [comment]
Yes I am. The report seems pretty old too :)

**Comment by gremo** [comment]
Well, I switched for testing to the integrated GPU of my Ryzen and if fact it works.

![Screenshot from 2023-09-29 19-30-31](https://github.com/sonnyp/Playhouse/assets/1532616/d18dbf72-7f75-4511-a529-52a37b98469c)
