### ISSUE TITLE
Needs an icon

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Playhouse#3]
And possibly a new name?

As analogy I liked the web thingy they have on playgrounds.

https://duckduckgo.com/?q=playground+web&t=h_&iax=images&ia=images

@bertob thoughts?

**Comment by bertob** [comment]
Not sure, I think that'd just look like a spiderweb at app icon sizes. Also, it'd probably be mostly ungeometric/off the pixel grid. How about a more generic colorful playground thing?

**Comment by bertob** [comment]
I do like the playground metaphor, but maybe we could change the name to a more specific playground thing and use that as the icon, e.g. something in this direction:
- Playpen
- Sandpit
- Playhouse
- Ballpark

**Comment by sonnyp** [comment]
What about Playhouse for the name and one of those house with triangle/circle/rectangle shapes that toddlers must fit.

Like this but way simpler https://www.jbd-jouetsenbois.com/en/fruity-house-shapes-fittinoung-xml-772-2623.html

I'm afraid it will look and feel like an app for children, thought.

**Comment by bertob** [comment]
I like that as a direction :+1: 

I guess we can try some icon ideas and decide based on what we can come up with for that. Perhaps the "app for children" problem could be avoided by e.g. having some HTML-related elements in the icon, e.g. some brackets on the play house.

**Comment by jimmac** [comment]
I've played with the idea of using colored baby building blocks for the icon. While not directly linked to web technologies, using the hexagon metally links it to cogged wheel, gears and bolts being a common engineering element.

![Playhouse 2](https://user-images.githubusercontent.com/14821/149532324-86b9ff0e-e469-42ae-9e7d-4061d624e389.png)
![Playhouse](https://user-images.githubusercontent.com/14821/149532340-93612b11-5896-43e9-a58b-578228566afe.png)
![Playhouse 1](https://user-images.githubusercontent.com/14821/149532356-6a91f447-76ea-41a6-bc75-2a2e05ae6cc1.png)

**Comment by sonnyp** [comment]
Looks neat - but - I plan on making an other "playground" app for GNOME tech (GJS/GTK/GLib/libadwaita/CSS/...) so emphasis on Web would be an easy way to differentiate both?

Or that new app could just use a very different metaphor. :thinking: Maybe something less playful and more serious - like Workshop

**Comment by jimmac** [comment]
Web sketchpad is another possible direction, but personally I like the playful kid blocks direction more
![Playhouse 3](https://user-images.githubusercontent.com/14821/149547555-37f1de30-331b-493d-899e-d9e43cc7f1e2.png)
.

**Comment by gitSaptarshi** [comment]
Why not name it 'Tinker' as the primary goal is to tinkering with HTML, CSS and JavaScript here.
Also the icon in the comment [#8](https://github.com/sonnyp/Playhouse/issues/3#issuecomment-1013257738) to me seems more inline with the app. I also think that making the page look like a puzzle block with a missing piece will make this concept even better.

**Comment by bertob** [comment]
This is what i had in mind originally, but i like the geometric blocks idea too.

![image](https://user-images.githubusercontent.com/1908896/149628778-652e4e9e-706b-44aa-8b4c-29f2c424bc0d.png)

**Comment by sonnyp** [comment]
Here is what @bertob came up with 

![re sonny Playhouse Source](https://user-images.githubusercontent.com/19673/192609495-87895846-851a-4adf-9de9-c474bc4ef7e5.svg)

**Comment by sonnyp** [comment]
based on @jimmac sketch
